In [1]:
import os 
import pandas as pd

In [2]:
os.chdir('../') # change directory

In [3]:
df = pd.read_csv('artifacts/data_preprocessing/preprocessedDataset.csv')

In [4]:


df.head()

,numeric__months_loan_duration,numeric__amount,numeric__percent_of_income,numeric__years_at_residence,numeric__age,numeric__existing_loans_count,numeric__dependents,categorical__checking_balance_< 0 DM,categorical__checking_balance_> 200 DM,categorical__checking_balance_unknown,...,categorical__employment_duration_unemployed,categorical__other_credit_none,categorical__other_credit_store,categorical__housing_own,categorical__housing_rent,categorical__job_skilled,categorical__job_unemployed,categorical__job_unskilled,categorical__phone_yes,categorical__default_yes
0,0.023256,0.050567,1.000000,1.000000,0.812500,0.333333,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.441860,0.313690,0.333333,0.333333,0.053571,0.000000,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,0.093023,0.101574,0.333333,0.666667,0.535714,0.000000,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.441860,0.419941,0.333333,1.000000,0.464286,0.000000,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.232558,0.254209,0.666667,1.000000,0.607143,0.333333,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [5]:
df.shape

(1000, 36)

In [6]:
df.columns

Index(['numeric__months_loan_duration', 'numeric__amount',
       'numeric__percent_of_income', 'numeric__years_at_residence',
       'numeric__age', 'numeric__existing_loans_count', 'numeric__dependents',
       'categorical__checking_balance_< 0 DM',
       'categorical__checking_balance_> 200 DM',
       'categorical__checking_balance_unknown',
       'categorical__credit_history_good',
       'categorical__credit_history_perfect',
       'categorical__credit_history_poor',
       'categorical__credit_history_very good', 'categorical__purpose_car',
       'categorical__purpose_car0', 'categorical__purpose_education',
       'categorical__purpose_furniture/appliances',
       'categorical__purpose_renovations',
       'categorical__savings_balance_500 - 1000 DM',
       'categorical__savings_balance_< 100 DM',
       'categorical__savings_balance_> 1000 DM',
       'categorical__savings_balance_unknown',
       'categorical__employment_duration_4 - 7 years',
       'categorical__employment_duration_< 1 year',
       'categorical__employment_duration_> 7 years',
       'categorical__employment_duration_unemployed',
       'categorical__other_credit_none', 'categorical__other_credit_store',
       'categorical__housing_own', 'categorical__housing_rent',
       'categorical__job_skilled', 'categorical__job_unemployed',
       'categorical__job_unskilled', 'categorical__phone_yes',
       'categorical__default_yes'],
      dtype='object')

In [9]:
# check the null values 

if df.isna().sum().sum() != 0:
    print("There are null values")
else:
    print("No null values ðŸ˜Š")

No null values ðŸ˜Š

In [15]:
#  check duplicate values 

if df.duplicated().sum() != 0:
    print("There are duplicated values")
else:
    print("No duplicated values ðŸ˜Š")

No duplicated values ðŸ˜Š

In [16]:
df.describe()

,numeric__months_loan_duration,numeric__amount,numeric__percent_of_income,numeric__years_at_residence,numeric__age,numeric__existing_loans_count,numeric__dependents,categorical__checking_balance_< 0 DM,categorical__checking_balance_> 200 DM,categorical__checking_balance_unknown,...,categorical__employment_duration_unemployed,categorical__other_credit_none,categorical__other_credit_store,categorical__housing_own,categorical__housing_rent,categorical__job_skilled,categorical__job_unemployed,categorical__job_unskilled,categorical__phone_yes,categorical__default_yes
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000
mean,0.189616,0.154127,0.657667,0.615000,0.294075,0.135667,0.155000,0.274000,0.063000,0.394000,...,0.062000,0.814000,0.047000,0.713000,0.179000,0.630000,0.022000,0.2000,0.404000,0.300000
std,0.123432,0.120344,0.372905,0.367906,0.197733,0.192551,0.362086,0.446232,0.243085,0.488879,...,0.241276,0.389301,0.211745,0.452588,0.383544,0.483046,0.146757,0.4002,0.490943,0.458487
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000
25%,0.093023,0.061379,0.333333,0.333333,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000
50%,0.162791,0.113871,0.666667,0.666667,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.0000,0.000000,0.000000
75%,0.232558,0.204812,1.000000,1.000000,0.410714,0.333333,0.000000,1.000000,0.000000,1.000000,...,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.0000,1.000000,1.000000
max,0.441860,0.419961,1.000000,1.000000,0.812500,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000

In [18]:
# target column 

df['categorical__default_yes'].value_counts()

categorical__default_yes
0.0    700
1.0    300
Name: count, dtype: int64